apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  #- https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v3.1.4/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
