name: 'quick-aws-eks terraform check'

on:
  push:
    paths:
      - 'quick-aws-eks-fleet/**'
    # paths-ignore:
    #   - '**.md'
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  
  terraform-security:
    #runs-on: arc-runner-set
    runs-on: ubuntu-latest
    name: Terraform security check
    steps:
    - name: Checkout
      uses: actions/checkout@v6
     
    - name: Change Directory
      run: cd quick-aws-eks-fleet

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Terrascan
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
        framework: terraform
        output_format: sarif
        skip_check: CKV_TF_1,CKV2_AWS_34,CKV_AWS_378

  terraform-format-validate:
    runs-on: ubuntu-latest
    name: Terraform Format and Validate
    needs: terraform-security
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Change Directory
      run: cd quick-aws-eks-fleet
   
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false